### ISSUE TITLE
change exchange moves

### ISSUE THREAD

**Issue by floswald** [floswald/MomentOpt.jl#22]
the exchange moves should be independent of the distance between chains i and j. it should only depend on whether the proposed chain j is acceptable on chain i:

```
# this
if algo.dist_fun(evj.value - evi.value)  < algo["maxdists"][i]
            swap_ev_ij!(algo,i,j)
        end

# becomes
if evj.value < algo["maxdists"][i]
            swap_ev_ij!(algo,i,j)
end
```

* need maybe to tighten up `MProb` to require only *maximization* or *minimization*

**Comment by edoardociscato** [comment]
I am trying this right now, and realized you have to be good when picking `algo["maxdists"]` otherwise you will have very little swaps and the burn-in phase becomes quite long. If `algo["maxdists"][1]` is too small, it will take quite a long time before other chains are able to pass down the information. Obviously, the more chains, the better this should work, but having many chains is not always possible. By the way, the BGP paper uses 15 chains and runs 750,000 iterations with 20% of them being the burn-in. And their problem is way easier than our models...

After yesterday's discussion, I thought that an alternative could be
```
# this
if algo.dist_fun(evj.value - evi.value)  < algo["maxdists"][i]
            swap_ev_ij!(algo,i,j)
        end

# becomes
if evj.value - evi.value < algo["maxdists"][i]
            swap_ev_ij!(algo,i,j)
end
```
so that hot chain j is swapped with cold chain i only if the difference `evj.value - evi.value` is small. Initially, you proposed to check `abs(evj.value - evi.value)` in order to decide if to swap: but this could also allow swaps if `evj.value` was worse than `evi.value` (not too much worse, depending on `"c.["maxdist"]`, but still worse).

I will try the alternative exchange rule that I propose above (starting with `algo["maxdists"][i]` equal to 0 on every chain as a benchmark) and will keep you posted.

**Comment by floswald** [comment]
any progress on this issue?

**Comment by edoardociscato** [comment]
I've been using what suggested in my last comment:
```
# this
if algo.dist_fun(evj.value - evi.value)  < algo["maxdists"][i]
            swap_ev_ij!(algo,i,j)
        end

# becomes
if evj.value - evi.value < algo["maxdists"][i]
            swap_ev_ij!(algo,i,j)
end
```
Note that in this way you can easily set `algo["maxdists"][i]` to zero on every chain and try out the plain exchange rule `evj.value < evi.value `. On the contrary, if you want to increase the number of exchange moves and explore the parameter space more more extensively, you can set larger `algo["maxdists"][i]`: however, this also implies a higher risk of moving away from the region of the global minimum. This trade-off should fade with many chains, whose number results in being crucial for the algorithm to work well.

After trying out this exchange rule, the algorithm is working decently for me. Even with many parameters, I can see some improvements: after a burnout phase, the coldest chain actually targets a small region where the global minimum is expected to be, while hottest chains keep moving. Most importantly, this rule also corresponds to what the BGP paper proposes, so I think it is worth implementing it in the package.

I can do a PR as soon as possible, should I proceed? I will also try to update the examples when I have time.

**Comment by floswald** [comment]
PR would be great. Please pull the most recent version of master before you
branch off.

**Comment by edoardociscato** [comment]
I am sorry @floswald this is EXACTLY what I did not do... I am trying to fix this right now, so that you can merge my pull request if you want.

**Comment by floswald** [comment]
argh. sorry about that!
